
version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  etl:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://etl_user:etl_pass@postgres:5432/etl_db
    volumes:
      - .:/app
volumes:
  pgdata:
